# Generated by Django 5.1.4 on 2024-12-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('Select', 'select'), ('silver', 'silver'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('orange', 'orange')], default='select', max_length=20)),
                ('cetegory', models.CharField(choices=[('Select', 'select'), ('leptop', 'leptop'), ('Ipad', 'Ipad'), ('phone', 'phone'), ('watch', 'watch')], default='select', max_length=25)),
                ('price', models.IntegerField(max_length=150)),
            ],
        ),
    ]
