# Generated by Django 5.1.4 on 2024-12-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_phone_name_of_phone_alter_phone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.CharField(choices=[('Select', 'select'), ('silver', 'Silver'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='Select', max_length=20),
        ),
    ]
