# Generated by Django 5.1.4 on 2024-12-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_phone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(default='description of the pohne ', max_length=500),
        ),
    ]
