# Generated by Django 5.1.4 on 2024-12-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_phone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='name_of_brand',
            field=models.CharField(default='', max_length=150),
        ),
    ]
