# Generated by Django 5.1.4 on 2024-12-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_phone_name_of_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='cetegory',
            new_name='cetegory_of_phone',
        ),
    ]
