# Generated by Django 5.1.4 on 2024-12-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_cetegory_phone_cetegory_of_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.CharField(choices=[('select', 'Select'), ('silver', 'Silve r'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(default='  ', max_length=500),
        ),
    ]
